# Generated by Django 3.2.4 on 2021-06-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20210608_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employ',
            name='empid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employ',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
