# Generated by Django 3.2.4 on 2021-06-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_auto_20210610_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
