# Generated by Django 3.2.4 on 2021-06-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_alter_employ_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employ',
            name='id',
        ),
        migrations.AlterField(
            model_name='employ',
            name='empid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
