# Generated by Django 3.2.4 on 2021-06-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_auto_20210611_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employ',
            name='fname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employ',
            name='lname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employ',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employ',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
