# Generated by Django 3.2.4 on 2021-06-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_auto_20210612_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employ',
            name='fname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employ',
            name='lname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employ',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employ',
            name='position',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Senior Developer', 'Senior Developer'), ('Junior Developer', 'Junior Developer'), ('HR', 'HR'), ('-', '-'), ('Test', 'Test')], default='-', max_length=16),
        ),
    ]
