# Generated by Django 3.2.4 on 2021-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0008_auto_20210612_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employ',
            name='email',
        ),
        migrations.AddField(
            model_name='employ',
            name='EmployID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employ',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employ',
            name='githubUsername',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employ',
            name='highestEducation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employ',
            name='personalEmail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employ',
            name='professionalEmail',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employ',
            name='mobile',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='employ',
            name='position',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Senior Developer', 'Senior Developer'), ('Junior Developer', 'Junior Developer'), ('HR', 'HR'), ('-', '-'), ('Test', 'Test')], max_length=16),
        ),
    ]
