# Generated by Django 3.2.4 on 2021-06-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0011_alter_employ_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='employ',
            name='joinedOn',
            field=models.DateField(auto_now=True, verbose_name='Joined On'),
        ),
    ]
