# Generated by Django 3.2.4 on 2021-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0012_employ_joinedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='employID',
            field=models.IntegerField(unique=True, verbose_name='Employ ID'),
        ),
    ]
