# Generated by Django 3.2.4 on 2021-06-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0013_alter_employ_employid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='education',
            field=models.CharField(max_length=80, verbose_name='Highest Education'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='joinedOn',
            field=models.DateField(verbose_name='Joined On'),
        ),
        migrations.AlterField(
            model_name='employ',
            name='mobile',
            field=models.IntegerField(unique=True, verbose_name='Mobile No'),
        ),
    ]
