# Generated by Django 3.2.4 on 2021-06-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0017_auto_20210616_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
