# Generated by Django 3.2.4 on 2021-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0021_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientID', models.AutoField(primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=40, verbose_name='Client Name')),
                ('clientAddress', models.TextField(verbose_name='Client Address')),
                ('clientEmail', models.EmailField(max_length=254, verbose_name='Client Email')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='userType',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Admin', 'Admin'), ('Staff', 'Staff'), ('Client', 'Client')], default='Regular', max_length=8),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='userType',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Admin', 'Admin'), ('Staff', 'Staff'), ('Client', 'Client')], default='Regular', max_length=8),
        ),
    ]
